#!/usr/bin/env python3

# (c) 2016-2020 GoodRobots
# http://github.com/goodrobots/visiond
# This is a simple python project that controls a video source, transmutes formats and transmits it over the network to various clients

import os

from modules.config import *
from modules.logger import *
from modules.app import *

if __name__ == "__main__":
    print("Starting visiond")

    # Setup config
    cwd = os.path.dirname(os.path.abspath(__file__))
    config = visiondConfig(os.path.join(cwd, 'visiond.conf'))

    # Setup logger
    logger = visiondLogger(cwd, config)
    
    # Create app instance and daemonize
    app = visiondApp(config)
    app.run()
